export const COMMON_VEGETABLES = [
  "Potato (Batata)",
  "Onion (Dungri)",
  "Tomato (Tameta)",
  "Ginger (Aadu)",
  "Garlic (Lasan)",
  "Green Chili (Marcha)",
  "Coriander (Kothmir)",
  "Lemon (Limbu)",
  "Cabbage (Kobi)",
  "Cauliflower (Fulawar)",
  "Brinjal (Ringan)",
  "Lady Finger (Bhinda)",
  "Bottle Gourd (Dudhi)",
  "Bitter Gourd (Karela)",
  "Ridge Gourd (Turiya)",
  "Sponge Gourd (Galaka)",
  "Ivy Gourd (Tindora)",
  "Pointed Gourd (Parval)",
  "Cluster Beans (Guvar)",
  "French Beans (Fansi)",
  "Green Peas (Vatana)",
  "Carrot (Gajar)",
  "Radish (Mulo)",
  "Cucumber ( કાકડી - Kakdi)",
  "Spinach (Palak)",
  "Fenugreek Leaves (Methi)",
  "Drumstick (Saragvo)",
  "Sweet Potato (Shakariya)",
  "Yam (Suran)",
  "Pumpkin (Kolum)",
  "Capsicum (Simla Marcha)",
  "Beetroot (Beet)",
  "Mint (Phudino)",
  "Curry Leaves (Limdo)",
  "Banana (Kela)",
  "Apple (Safarchand)",
  "Mango (Keri)",
  "Grapes (Draksh)",
  "Papaya (Papaiya)",
  "Watermelon (Tarbuch)",
  "Pomegranate (Dadam)"
];
